services:
  - type: web
    name: youtube-downloader
    env: node
    buildCommand: |
      apt-get update
      apt-get install -y python3 python3-pip ffmpeg
      pip3 install yt-dlp
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 16
